### PR TITLE
Relocate remaining ui components

### PR DESCRIPTION
**Pull request by quantumjockey**
I realized while doing this that a couple of the components are still in class format and will change that in a future pull request. I'm not sure if I have access to the CI dashboard but I've gotten a few emails saying this branch fails. @shicholas When you can, let me know what's failing CI on this branch and I'll correct it promptly thereafter.

### CODE REVIEW

**Comment by shicholas** [comment]
Does this URL not work? https://circleci.com/gh/1337lawyers/design/715?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by shicholas** [comment]
here's the error:


```
ERR! Module not found: Error: Can't resolve './components/Navbar/navbar' in '/home/circleci/project/src'
```

this happens when running `yarn build-storybook`

**Comment by quantumjockey** [comment]
@shicolas It does - I didn't realize it was linked until right after I wrote the first comment.

**Comment by quantumjockey** [comment]
@shicholas Running `yarn build-storybook` locally now to check

**Comment by quantumjockey** [comment]
All tests pass locally at least

**Comment by quantumjockey** [comment]
@shicholas The command 'yarn build-storybook' passes locally and so do all the unit test stubs. Checking if there's a way to flush the cache in the CI dashboard.

**Comment by quantumjockey** [comment]
@shicholas I corrected the folder name locally while I was working on it but apparently that change wasn't detected in Git, so I temporarily changed the name of the folder and changed it back. Seems to have worked! Everything still builds & tests successfully locally.

**Comment by shicholas** [comment]
My first guess is because `children` in react usually refer to the child components like:

```
<Container children={{}} />
```

could be

```
<Container>
  <h1>A header</h1>
</Container>
```

That being said, this is great as is. I'll merge.

**Pull request merged**
