### PR TITLE
Add L33tForm markup to existing L33tSetup forms

### PR DESCRIPTION
**Pull request by quantumjockey**
@shicholas I'm not sure if an approach like this was the long-term plan but I'm putting this here for exploration. Thankfully it was quick and straightforward. The form control itself seems to have issues submitting via the `<SubmitAndReset />` component because it tries operating on a `_blank` target. Needs a little more testing for sure. 

Positioned as a diff against [shift+enter-to-submit-form-#96](https://github.com/1337lawyers/design/tree/shift+enter-to-submit-form-%2396) temporarily for brevity but is intended to either merge directly into [master](https://github.com/1337lawyers/design/tree/master) after the other branch has already been merged.

### CODE REVIEW

**Comment by shicholas** [comment]
lgtm, please fix linting issue

**Comment by quantumjockey** [comment]
@shicholas I cleaned things up and resolved the few fixable linting issues showing in tslint. There were a couple of tslint errors without resolutions - like recognizing the `Object` type in JS but throwing en error as if expecting an explicitly defined type within the source code. It still seems to work though.

**Comment by quantumjockey** [comment]
Also, I think CircleCI is failing the test task because each test seems to time out after 10 seconds and one of them is taking 12 seconds to complete.

**Comment by quantumjockey** [comment]
Also, the issue with `<SubmitAndReset />` has been fixed too. It didn't validate on the `Yup` object and so enabled the 'submit' button by default. To resolve this, it now tests for empty fields before activating the `disabled` attribute on the Submit button via the following added statement:
`
Object.values(values).every(value => {
    return value === '';
})
`
Conditional rendering of the `Reset` button is also facilitated by nullifying the `handleReset` prop.
`
{handleReset && (
      <div className="control">
        <button className="button is-light" onClick={handleReset} type="button">
          Reset
        </button>
      </div>
    )}
`

**Comment by cryptomoovin** [comment]
@quantumjockey in what order should I review & merge these PRs? Looks like this is supposed to be merged into #161?

**Comment by quantumjockey** [comment]
Hey @cryptomoovin! If you approve of the changes, please merge this one first, then [#161](https://github.com/1337lawyers/design/pull/161). I'm still working on [#163](https://github.com/1337lawyers/design/pull/163) and should have it figured out by tomorrow night. If you merge these I'll just update [#163](https://github.com/1337lawyers/design/pull/163) to merge into [master](https://github.com/1337lawyers/design/tree/master).

**Comment by shicholas** [comment]
okay, please update the build here then I'll merge this than #161. maybe we can do #163 on master

**Comment by quantumjockey** [comment]
@shicholas Build issue fixed! Apologies for the delay

**Comment by shicholas** [comment]
no worries, thanks!

**Pull request merged**
